name: pre-commit

on: [push]

jobs:
  run-precommit:
    runs-on: [ecs-hosted]
    container:
      image: python:3.9
    steps:
    - uses: actions/checkout@v4
    #download pre-commit zipapp 
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: flake8 --all-files
    - run: ls -lah
      shell: bash
